 clear;clc;close all;
video_base_path = '/media/sunx/Data/ImageNet/train';
annotation_base_path = '/media/sunx/Data/ImageNet/Annotations';
mid_result_path = '/media/sunx/Data/ImageNet/mid_result';
output_path = '/home/sunx/output/ours';
% video_list = load('video_list.mat');
% video_list = video_list.video_list;
time_table = run_all1(video_base_path,mid_result_path,output_path,annotation_base_path);
frame_time_cost = double(sum(time_table(:,1))) / double(sum(time_table(:,2)));
fprintf('avg time cost : %.2f s.', frame_time_cost);
save('ours_time_10_video.mat',time_table);
